### PR TITLE
basic implementation of facesmash

### PR DESCRIPTION
**Pull request by SkroX**

### CODE REVIEW

**Comment by ThisIsNSH** [comment]
bro git reset --soft HEAD~1 karo
then git add <filename>
dont app gradle file
push again

**Comment by ThisIsNSH** [comment]
delete this branch (from github) 
before pushing new work

**Comment by SkroX** [comment]
Sir master branch me hi merge krdu?

**Comment by ThisIsNSH** [comment]
> Sir master branch me hi merge krdu?

Kaise hoga Shubhu Baby? Conflict hai na! 😅
Kardo ho jaye toh 🤗

**Pull request closed without merging**
